/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:1e9692a5-2351-4307-a378-c3d7a136bbd6",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_LWypTEpqG",
    "aws_user_pools_web_client_id": "32osj5fls6j9mi8ajl4t1kr8te",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "REGION": "eu-central-1",
    "USER_POOL_ID": "eu-central-1_TJjOBFR6J",
    "USER_POOL_APP_CLIENT_ID": "6asd7ut9vvkjmc38l6n02ekscn"
};


export default awsmobile;
